doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/User/Domain'
                prefix: 'App\User\Domain'
                alias: App
            Entity:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: Entity

            DayOff:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/DayOff/Domain/ValueObject'
                prefix: 'App\DayOff\Domain\ValueObject'
                alias: Embeddable
            CalendarEmbeddable:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Calendar/Domain/ValueObject'
                prefix: 'App\Calendar\Domain\ValueObject'
                alias: CalendarEmbeddable
            TypeDayOffEmbeddable:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/TypeDayOff/Domain/ValueObject'
                prefix: 'App\TypeDayOff\Domain\ValueObject'
                alias: TypeDayOffEmbeddable