# * Company Module
app_company_management:
    path: /company/management
    controller: App\Company\Infrastructure\Controller\CompanyManagementController::index

app_add_department:
    path: /company/management/add/department
    controller: App\Company\Infrastructure\Controller\CompanyManagementController::addDepartment

# * Calendar Module
app_calendar_config_by_id:
    path: /calendar/management/config/{id}
    controller: App\Calendar\Infrastructure\Controller\CalendarConfigByCalendarId::index

app_calendar_management:
    path: /calendar/management
    controller: App\Calendar\Infrastructure\Controller\CalendarManagementController::index

app_create_calendar:
    path: /calendar/management/create/calendar
    controller: App\Calendar\Infrastructure\Controller\CreateCalendarController::create

app_dayoff_request_update:
    path: /calendar/management/dayoffrequest
    controller: App\Calendar\Infrastructure\Controller\DayOffRequestUpdaterController::updateDayOffRequest

app_edit_calendar:
    path: /calendar/management/edit/calendar
    controller: App\Calendar\Infrastructure\Controller\EditCalendarConfigController::edit

app_workdays_update:
    path: /calendar/management/update/workDays
    controller: App\Calendar\Infrastructure\Controller\WorkDaysUpdaterController::updateWorkDays

# * DayOffForm Supervisor Module
app_notification_supervise_approve:
    path: /supervise/management/notification/approve
    controller: App\DayOffForm\Infrastructure\Controller\Supervisor\ApproveNotificationEmployeesController::dayOff

app_notification_supervise_denied:
    path: /supervise/management/notification/deny
    controller: App\DayOffForm\Infrastructure\Controller\Supervisor\DenyNotificationEmployeesController::dayOff

app_supervise_management_find_employees:
    path: /supervise/management/dayoff/employees/filter
    controller: App\DayOffForm\Infrastructure\Controller\Supervisor\FilterDayOffByDepartmentByName::findUserInDayOff

app_supervise_dayoff_user:
    path: /supervise/management/dayoff/user/{id}
    controller: App\DayOffForm\Infrastructure\Controller\Supervisor\FilterDayOffFormByUserId::findUserInDayOffForm

app_dayoff_notification:
    path: /supervise/management/notification/employees/dayoff/{id}
    controller: App\DayOffForm\Infrastructure\Controller\Supervisor\SuperviseEmployeesByDayOffController::dayOff

app_notifications_list:
    path: /supervise/management/notification/list
    controller: App\DayOffForm\Infrastructure\Controller\Supervisor\ViewNotificationsListEmployeesController::index

app_supervise_day_off_employee:
    path: /supervise/management/dayoff/employees
    controller: App\DayOffForm\Infrastructure\Controller\Supervisor\SearchDayOffByUserController::index
    
# * DayOffForm Module
app_dashboard:
    path: /dashboard
    controller: App\DayOffForm\Infrastructure\Controller\DayOffForm\DashboardController::index

app_dayoff_config:
    path: /dayoff/request/{id}
    controller: App\DayOffForm\Infrastructure\Controller\DayOffForm\DayOffFormByCalendarController::index

app_dayoff:
    path: /dayoff/request
    controller: App\DayOffForm\Infrastructure\Controller\DayOffForm\DayOffFormController::index

app_dayoff_request:
    path: /dayoff/request/management/add
    controller: App\DayOffForm\Infrastructure\Controller\DayOffForm\DayOffRequestController::dayOff