# * Company Module
app_company_management:
    path: /company/management
    controller: App\Company\Infrastructure\Controller\CompanyManagementController::index

app_add_department:
    path: /company/management/add/department
    controller: App\Company\Infrastructure\Controller\CompanyManagementController::addDepartment

app_edit_company_management:
    path: /company/management/edit/{id}
    controller: App\Company\Infrastructure\Controller\EditCompanyManagementController::index

# * Department Module
app_department_name_update:
    path: /company/management/edit/department/name
    controller: App\Department\Infrastructure\Controller\DepartmentNameUpdaterController::departmentNameUpdate

app_department_code_update:
    path: /company/management/edit/department/code
    controller: App\Department\Infrastructure\Controller\DepartmentCodeUpdaterController::departmentCodeUpdate
    
# * Calendar Module
app_calendar_config_by_id:
    path: /calendar/management/config/{id}
    controller: App\Calendar\Infrastructure\Controller\CalendarConfigByCalendarId::index

app_calendar_management:
    path: /calendar/management
    controller: App\Calendar\Infrastructure\Controller\CalendarManagementController::index

app_create_calendar:
    path: /calendar/management/create/calendar
    controller: App\Calendar\Infrastructure\Controller\CreateCalendarController::create

app_dayoff_request_update:
    path: /calendar/management/dayoffrequest
    controller: App\Calendar\Infrastructure\Controller\DayOffRequestUpdaterController::updateDayOffRequest

app_edit_calendar:
    path: /calendar/management/edit/calendar
    controller: App\Calendar\Infrastructure\Controller\EditCalendarConfigController::edit

app_workdays_update:
    path: /calendar/management/update/workDays
    controller: App\Calendar\Infrastructure\Controller\WorkDaysUpdaterController::updateWorkDays

# * Feastday Module
app_feastday_create:
    path: /calendar/management/add/feastday
    controller: App\Feastday\Infrastructure\Controller\FeastdayCreatorController::feastdayCreate

app_feastday_delete:
    path: /calendar/management/delete/feastday
    controller: App\Feastday\Infrastructure\Controller\FeastdayDeleterController::feastdayDelete

# * TypeDayOff Module
app_typeDayOff_update:
    path: /calendar/management/typeDayOff
    controller: App\TypeDayOff\Infrastructure\Controller\TypeDayOffNumerUpdaterController::typeDayOffNumberUpdater

# * DayOffForm Supervisor Module
app_notification_supervise_approve:
    path: /supervise/management/notification/approve
    controller: App\DayOffForm\Infrastructure\Controller\Supervisor\ApproveNotificationEmployeesController::dayOff

app_notification_supervise_denied:
    path: /supervise/management/notification/deny
    controller: App\DayOffForm\Infrastructure\Controller\Supervisor\DenyNotificationEmployeesController::dayOff

app_supervise_management_find_employees:
    path: /supervise/management/dayoff/employees/filter
    controller: App\DayOffForm\Infrastructure\Controller\Supervisor\FilterDayOffByDepartmentByName::findUserInDayOff

app_supervise_dayoff_user:
    path: /supervise/management/dayoff/user/{id}
    controller: App\DayOffForm\Infrastructure\Controller\Supervisor\FilterDayOffFormByUserId::findUserInDayOffForm

app_dayoff_notification:
    path: /supervise/management/notification/employees/dayoff/{id}
    controller: App\DayOffForm\Infrastructure\Controller\Supervisor\SuperviseEmployeesByDayOffController::dayOff

app_notifications_list:
    path: /supervise/management/notification/list
    controller: App\DayOffForm\Infrastructure\Controller\Supervisor\ViewNotificationsListEmployeesController::index

app_supervise_day_off_employee:
    path: /supervise/management/dayoff/employees
    controller: App\DayOffForm\Infrastructure\Controller\Supervisor\SearchDayOffByUserController::index
    
# * DayOffForm Module
app_dashboard:
    path: /dashboard
    controller: App\DayOffForm\Infrastructure\Controller\DayOffForm\DashboardController::index

app_dayoff_config:
    path: /dayoff/request/{id}
    controller: App\DayOffForm\Infrastructure\Controller\DayOffForm\DayOffFormByCalendarController::index

app_dayoff:
    path: /dayoff/request
    controller: App\DayOffForm\Infrastructure\Controller\DayOffForm\DayOffFormController::index

app_dayoff_request:
    path: /dayoff/request/management/add
    controller: App\DayOffForm\Infrastructure\Controller\DayOffForm\DayOffRequestController::dayOff

# * User Module
app_login:
    path: /login
    controller: App\User\Infrastructure\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\User\Infrastructure\Controller\SecurityController::logout

app_register:
    path: /user/management/register
    controller: App\User\Infrastructure\Controller\RegistrationController::register

app_user_delete:
    path: /user/management/delete/{id}
    controller: App\User\Infrastructure\Controller\UserDeleterController::userDelete

app_user_rol_update:
    path: /user/management/rol
    controller: App\User\Infrastructure\Controller\UserRoleEditorController::userRoleUpdate

app_filtering_user_by_department:
    path: /user/management/filtering
    controller: App\User\Infrastructure\Controller\UserSearcherByDepartmentController::filteringUserByDepartment

app_filtering_user_by_id:
    path: /user/management/filter/id/{id}
    controller: App\User\Infrastructure\Controller\UserSearcherByIdController::getUserFormById

app_user_searcher_view:
    path: /user/management/edit/view
    controller: App\User\Infrastructure\Controller\UserSearcherViewController::index